"""operations add

Revision ID: 419517182167
Revises: ffa3c3528e47
Create Date: 2022-08-01 13:37:21.079169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '419517182167'
down_revision = 'ffa3c3528e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('replacement', sa.String(), nullable=True),
    sa.Column('cost', sa.String(), nullable=True),
    sa.Column('equipment_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_code'], ['equipments.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operations_id'), 'operations', ['id'], unique=True)
    op.create_index(op.f('ix_operations_replacement'), 'operations', ['replacement'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operations_replacement'), table_name='operations')
    op.drop_index(op.f('ix_operations_id'), table_name='operations')
    op.drop_table('operations')
    # ### end Alembic commands ###
