"""operations add column

Revision ID: 515dc6ebc50d
Revises: 419517182167
Create Date: 2022-08-01 14:19:17.712148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '515dc6ebc50d'
down_revision = '419517182167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operations', sa.Column('type', sa.String(), nullable=True))
    op.add_column('operations', sa.Column('code', sa.String(), nullable=True))
    op.drop_index('ix_operations_replacement', table_name='operations')
    op.create_index(op.f('ix_operations_type'), 'operations', ['type'], unique=False)
    op.drop_constraint('operations_equipment_code_fkey', 'operations', type_='foreignkey')
    op.create_foreign_key(None, 'operations', 'equipments', ['code'], ['code'])
    op.drop_column('operations', 'replacement')
    op.drop_column('operations', 'equipment_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operations', sa.Column('equipment_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('operations', sa.Column('replacement', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'operations', type_='foreignkey')
    op.create_foreign_key('operations_equipment_code_fkey', 'operations', 'equipments', ['equipment_code'], ['code'])
    op.drop_index(op.f('ix_operations_type'), table_name='operations')
    op.create_index('ix_operations_replacement', 'operations', ['replacement'], unique=False)
    op.drop_column('operations', 'code')
    op.drop_column('operations', 'type')
    # ### end Alembic commands ###
