name: Tests

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        plan: ["pylint", "flake8", "pytest"]
    env:
      POSTGRES_HOST: "localhost"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "db"
      POSTGRES_PASSWORD: "password"
    services:
      postgres:
        image: docker.io/postgres:14.4-alpine
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: "password"
          POSTGRES_DB: "db"
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      # checkout
    - uses: actions/checkout@v3
      # install python
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
      # install poetry
    - name: Install Poetry
      uses: snok/install-poetry@v1.3.1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
    - name: Install dependencies
      run: |
        poetry install --no-interaction
    - name: Run analysis and test
      run: |
        poetry run ${{ matrix.plan }} app
